# Generated by Django 4.1.3 on 2022-11-10 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_tour1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tour1',
        ),
    ]
