# Generated by Django 4.1.3 on 2022-11-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
