# Generated by Django 4.1.3 on 2022-11-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_agent_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='last_name',
            new_name='name_last_name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='name',
        ),
    ]
